# Use an official Node runtime as a parent image
FROM node:latest

# Set the working directory in the container
WORKDIR /app

# Copy the rest of your project
COPY . .

# Expose ports for frontend and backend
EXPOSE 3000 3001

CMD ["/bin/bash"]